version: '3'
networks:
  handgame:
services:
  handgame-api:
    image: handgame/handgame-api:0.1
    container_name: handgame-api
    hostname: handgame-api
    networks: &networks
      - handgame
    ports:
      - "17777:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/service.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "handgame"
      HANDGAME_OtelSampling__Strategy: Probability
      HANDGAME_OtelSampling__Probability: 0.5
      HANDGAME_Jaeger__AgentHost: jaeger
      HANDGAME_Jaeger__AgentPort: 6831
  jaeger:
    image: jaegertracing/all-in-one:1.45.0
    container_name: handgame-jaeger
    hostname: jaeger
    networks: *networks
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: handgame-prometheus
    hostname: prometheus
    networks: *networks
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
