global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "handgame"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    enable_http2: true
    metrics_path: /metrics
    static_configs:
      - targets:
        - "host.docker.internal:17777" # handgame-api
